import type { JourneyBook, JourneyLanguage } from "./types";

type Localized = Record<JourneyLanguage, string>;
const languages: JourneyLanguage[] = ["pt-PT", "en", "es", "fr", "it", "de"];
const localized = (values: [string, string, string, string, string, string]): Localized => Object.fromEntries(languages.map((language, index) => [language, values[index]])) as Localized;

const authors: Record<string, Localized> = {
  "2-chronicles": localized(["Tradicionalmente atribuído a Esdras; compilador não identificado", "Traditionally attributed to Ezra; final compiler unidentified", "Tradicionalmente atribuido a Esdras; compilador final no identificado", "Traditionnellement attribué à Esdras ; compilateur final non identifié", "Tradizionalmente attribuito a Esdra; compilatore finale non identificato", "Traditionell Esra zugeschrieben; endgültiger Verfasser unbekannt"]),
  ezra: localized(["Esdras e um compilador posterior", "Ezra and a later compiler", "Esdras y un compilador posterior", "Esdras et un compilateur ultérieur", "Esdra e un compilatore successivo", "Esra und ein späterer Bearbeiter"]),
  nehemiah: localized(["Neemias e um compilador posterior", "Nehemiah and a later compiler", "Nehemías y un compilador posterior", "Néhémie et un compilateur ultérieur", "Neemia e un compilatore successivo", "Nehemia und ein späterer Bearbeiter"]),
  esther: localized(["Autor não identificado", "Author not identified", "Autor no identificado", "Auteur non identifié", "Autore non identificato", "Autor nicht identifiziert"]),
  job: localized(["Autor não identificado", "Author not identified", "Autor no identificado", "Auteur non identifié", "Autore non identificato", "Autor nicht identifiziert"]),
  psalms: localized(["David, Asafe, filhos de Corá, Salomão, Moisés e outros", "David, Asaph, sons of Korah, Solomon, Moses and others", "David, Asaf, hijos de Coré, Salomón, Moisés y otros", "David, Asaph, fils de Coré, Salomon, Moïse et d'autres", "Davide, Asaf, figli di Core, Salomone, Mosè e altri", "David, Asaf, Söhne Korachs, Salomo, Mose und weitere"]),
  proverbs: localized(["Salomão, Agur, Lemuel e outros sábios", "Solomon, Agur, Lemuel and other sages", "Salomón, Agur, Lemuel y otros sabios", "Salomon, Agur, Lemuel et d'autres sages", "Salomone, Agur, Lemuel e altri saggi", "Salomo, Agur, Lemuel und andere Weise"]),
  ecclesiastes: localized(["Qohelet; tradicionalmente identificado com Salomão", "Qoheleth; traditionally identified with Solomon", "Qohelet; tradicionalmente identificado con Salomón", "Qohélet ; traditionnellement identifié à Salomon", "Qoèlet; tradizionalmente identificato con Salomone", "Kohelet; traditionell mit Salomo identifiziert"]),
  "song-of-songs": localized(["Tradicionalmente atribuído a Salomão", "Traditionally attributed to Solomon", "Tradicionalmente atribuido a Salomón", "Traditionnellement attribué à Salomon", "Tradizionalmente attribuito a Salomone", "Traditionell Salomo zugeschrieben"]),
  isaiah: localized(["Isaías, filho de Amoz", "Isaiah son of Amoz", "Isaías hijo de Amoz", "Ésaïe, fils d'Amots", "Isaia, figlio di Amoz", "Jesaja, Sohn des Amoz"]),
  jeremiah: localized(["Jeremias, com a colaboração de Baruque", "Jeremiah, with the assistance of Baruch", "Jeremías, con la colaboración de Baruc", "Jérémie, avec la collaboration de Baruch", "Geremia, con la collaborazione di Baruc", "Jeremia, unter Mitwirkung Baruchs"]),
  lamentations: localized(["Autor não identificado; tradicionalmente atribuído a Jeremias", "Author unidentified; traditionally attributed to Jeremiah", "Autor no identificado; tradicionalmente atribuido a Jeremías", "Auteur non identifié ; traditionnellement attribué à Jérémie", "Autore non identificato; tradizionalmente attribuito a Geremia", "Autor unbekannt; traditionell Jeremia zugeschrieben"]),
  ezekiel: localized(["Ezequiel, sacerdote e profeta", "Ezekiel, priest and prophet", "Ezequiel, sacerdote y profeta", "Ézéchiel, prêtre et prophète", "Ezechiele, sacerdote e profeta", "Hesekiel, Priester und Prophet"]),
  daniel: localized(["Tradicionalmente atribuído a Daniel", "Traditionally attributed to Daniel", "Tradicionalmente atribuido a Daniel", "Traditionnellement attribué à Daniel", "Tradizionalmente attribuito a Daniele", "Traditionell Daniel zugeschrieben"]),
  hosea: localized(["Oseias, filho de Beeri", "Hosea son of Beeri", "Oseas hijo de Beeri", "Osée, fils de Beéri", "Osea, figlio di Beeri", "Hosea, Sohn Beeris"]),
  joel: localized(["Joel, filho de Petuel", "Joel son of Pethuel", "Joel hijo de Petuel", "Joël, fils de Petouel", "Gioele, figlio di Petuel", "Joel, Sohn Petuëls"]),
  amos: localized(["Amós, pastor de Tecoa", "Amos, shepherd from Tekoa", "Amós, pastor de Tecoa", "Amos, berger de Tékoa", "Amos, pastore di Tekoa", "Amos, Hirte aus Tekoa"]),
  obadiah: localized(["Obadias", "Obadiah", "Abdías", "Abdias", "Abdia", "Obadja"]),
  jonah: localized(["Jonas, filho de Amitai", "Jonah son of Amittai", "Jonás hijo de Amitai", "Jonas, fils d'Amittaï", "Giona, figlio di Amittai", "Jona, Sohn Amittais"]),
  micah: localized(["Miqueias de Moresete", "Micah of Moresheth", "Miqueas de Moreset", "Michée de Morésheth", "Michea di Moreset", "Micha aus Moreschet"]),
  nahum: localized(["Naum de Elcós", "Nahum the Elkoshite", "Nahúm de Elcós", "Nahum d'Elqosh", "Naum di Elcos", "Nahum aus Elkosch"]),
  habakkuk: localized(["Habacuque, o profeta", "Habakkuk the prophet", "Habacuc, el profeta", "Habacuc, le prophète", "Abacuc, il profeta", "Habakuk, der Prophet"]),
  zephaniah: localized(["Sofonias, filho de Cusi", "Zephaniah son of Cushi", "Sofonías hijo de Cusí", "Sophonie, fils de Koushi", "Sofonia, figlio di Cusi", "Zefanja, Sohn Kuschis"]),
  haggai: localized(["Ageu, o profeta", "Haggai the prophet", "Hageo, el profeta", "Aggée, le prophète", "Aggeo, il profeta", "Haggai, der Prophet"]),
  zechariah: localized(["Zacarias, filho de Berequias", "Zechariah son of Berechiah", "Zacarías hijo de Berequías", "Zacharie, fils de Bérékia", "Zaccaria, figlio di Berechia", "Sacharja, Sohn Berechjas"]),
  malachi: localized(["Malaquias; identidade pessoal incerta", "Malachi; personal identity uncertain", "Malaquías; identidad personal incierta", "Malachie ; identité personnelle incertaine", "Malachia; identità personale incerta", "Maleachi; persönliche Identität unsicher"]),
  matthew: localized(["Tradicionalmente atribuído a Mateus, o apóstolo", "Traditionally attributed to Matthew the apostle", "Tradicionalmente atribuido a Mateo, el apóstol", "Traditionnellement attribué à Matthieu, l'apôtre", "Tradizionalmente attribuito a Matteo, l'apostolo", "Traditionell dem Apostel Matthäus zugeschrieben"]),
  mark: localized(["Tradicionalmente atribuído a João Marcos", "Traditionally attributed to John Mark", "Tradicionalmente atribuido a Juan Marcos", "Traditionnellement attribué à Jean-Marc", "Tradizionalmente attribuito a Giovanni Marco", "Traditionell Johannes Markus zugeschrieben"]),
  luke: localized(["Tradicionalmente atribuído a Lucas, médico e companheiro de Paulo", "Traditionally attributed to Luke, physician and companion of Paul", "Tradicionalmente atribuido a Lucas, médico y compañero de Pablo", "Traditionnellement attribué à Luc, médecin et compagnon de Paul", "Tradizionalmente attribuito a Luca, medico e compagno di Paolo", "Traditionell Lukas, Arzt und Begleiter des Paulus, zugeschrieben"]),
  john: localized(["Tradicionalmente atribuído a João, o apóstolo", "Traditionally attributed to John the apostle", "Tradicionalmente atribuido a Juan, el apóstol", "Traditionnellement attribué à Jean, l'apôtre", "Tradizionalmente attribuito a Giovanni, l'apostolo", "Traditionell dem Apostel Johannes zugeschrieben"]),
  acts: localized(["Tradicionalmente atribuído a Lucas, médico e companheiro de Paulo", "Traditionally attributed to Luke, physician and companion of Paul", "Tradicionalmente atribuido a Lucas, médico y compañero de Pablo", "Traditionnellement attribué à Luc, médecin et compagnon de Paul", "Tradizionalmente attribuito a Luca, medico e compagno di Paolo", "Traditionell Lukas, Arzt und Begleiter des Paulus, zugeschrieben"]),
  hebrews: localized(["Autor não identificado", "Author not identified", "Autor no identificado", "Auteur non identifié", "Autore non identificato", "Autor nicht identifiziert"]),
  james: localized(["Tradicionalmente atribuído a Tiago, irmão de Jesus", "Traditionally attributed to James, brother of Jesus", "Tradicionalmente atribuido a Santiago, hermano de Jesús", "Traditionnellement attribué à Jacques, frère de Jésus", "Tradizionalmente attribuito a Giacomo, fratello di Gesù", "Traditionell Jakobus, dem Bruder Jesu, zugeschrieben"]),
  "1-peter": localized(["Tradicionalmente atribuído ao apóstolo Pedro", "Traditionally attributed to the apostle Peter", "Tradicionalmente atribuido al apóstol Pedro", "Traditionnellement attribué à l'apôtre Pierre", "Tradizionalmente attribuito all'apostolo Pietro", "Traditionell dem Apostel Petrus zugeschrieben"]),
  "2-peter": localized(["Tradicionalmente atribuído ao apóstolo Pedro", "Traditionally attributed to the apostle Peter", "Tradicionalmente atribuido al apóstol Pedro", "Traditionnellement attribué à l'apôtre Pierre", "Tradizionalmente attribuito all'apostolo Pietro", "Traditionell dem Apostel Petrus zugeschrieben"]),
  "1-john": localized(["Tradicionalmente atribuído ao apóstolo João", "Traditionally attributed to the apostle John", "Tradicionalmente atribuido al apóstol Juan", "Traditionnellement attribué à l'apôtre Jean", "Tradizionalmente attribuito all'apostolo Giovanni", "Traditionell dem Apostel Johannes zugeschrieben"]),
  "2-john": localized(["O Ancião; tradicionalmente identificado com o apóstolo João", "The Elder; traditionally identified with the apostle John", "El Anciano; tradicionalmente identificado con el apóstol Juan", "L'Ancien ; traditionnellement identifié à l'apôtre Jean", "L'Anziano; tradizionalmente identificato con l'apostolo Giovanni", "Der Älteste; traditionell mit dem Apostel Johannes identifiziert"]),
  "3-john": localized(["O Ancião; tradicionalmente identificado com o apóstolo João", "The Elder; traditionally identified with the apostle John", "El Anciano; tradicionalmente identificado con el apóstol Juan", "L'Ancien ; traditionnellement identifié à l'apôtre Jean", "L'Anziano; tradizionalmente identificato con l'apostolo Giovanni", "Der Älteste; traditionell mit dem Apostel Johannes identifiziert"]),
  jude: localized(["Tradicionalmente atribuído a Judas, irmão de Tiago", "Traditionally attributed to Jude, brother of James", "Tradicionalmente atribuido a Judas, hermano de Santiago", "Traditionnellement attribué à Jude, frère de Jacques", "Tradizionalmente attribuito a Giuda, fratello di Giacomo", "Traditionell Judas, dem Bruder des Jakobus, zugeschrieben"]),
  revelation: localized(["João de Patmos; tradicionalmente identificado com o apóstolo João", "John of Patmos; traditionally identified with the apostle John", "Juan de Patmos; tradicionalmente identificado con el apóstol Juan", "Jean de Patmos ; traditionnellement identifié à l'apôtre Jean", "Giovanni di Patmos; tradizionalmente identificato con l'apostolo Giovanni", "Johannes von Patmos; traditionell mit dem Apostel Johannes identifiziert"]),
};

export function applyJourneyAuthorAttributions(book: JourneyBook): JourneyBook {
  const attribution = authors[book.slug];
  if (!attribution) return book;
  return { ...book, overview: Object.fromEntries(languages.map(language => [language, { ...book.overview[language], author: attribution[language] }])) as JourneyBook["overview"] };
}

export const journeyAuthorAttributions = authors;
