import type { JourneyChapter, JourneyLanguage } from "./types";

const titles: Record<JourneyLanguage, string[]> = {
  "pt-PT": ["Israel multiplica-se no Egito","O nascimento de Moisés","A sarça ardente","Moisés regressa ao Egito","O primeiro encontro com o Faraó","Deus reafirma a promessa","A primeira praga","Rãs, mosquitos e moscas","Pestes, úlceras e granizo","Gafanhotos, trevas e o anúncio da morte","A última praga é anunciada","A Páscoa e a saída do Egito","Consagração dos primogénitos","A travessia do mar","O cântico de Moisés e Miriam","Maná e codornizes","Água da rocha e batalha contra Amaleque","O conselho de Jetro","Israel chega ao Sinai","Os Dez Mandamentos","Leis sobre servos e violência","Leis sobre propriedade e justiça","Justiça, descanso e festas","A aliança é confirmada","Ofertas para o santuário","A arca e o mobiliário","O altar e o pátio","As vestes sacerdotais","A consagração dos sacerdotes","O altar do incenso e o resgate","Bezalel, o sábado e as tábuas","O bezerro de ouro","Moisés intercede por Israel","As novas tábuas da aliança","O sábado e as ofertas","A construção do tabernáculo","A arca, a mesa e o candelabro","Os altares e o pátio","As vestes sacerdotais concluídas","A glória enche o tabernáculo"],
  en: ["Israel multiplies in Egypt","The birth of Moses","The burning bush","Moses returns to Egypt","The first meeting with Pharaoh","God reaffirms the promise","The first plague","Frogs, gnats and flies","Plagues, boils and hail","Locusts, darkness and the warning of death","The final plague announced","Passover and the departure from Egypt","Consecration of the firstborn","Crossing the sea","The song of Moses and Miriam","Manna and quail","Water from the rock and Amalek","Jethro's advice","Israel arrives at Sinai","The Ten Commandments","Laws about servants and violence","Laws about property and justice","Justice, rest and festivals","The covenant confirmed","Offerings for the sanctuary","The ark and furnishings","The altar and courtyard","The priestly garments","Consecration of the priests","The incense altar and ransom","Bezalel, Sabbath and the tablets","The golden calf","Moses intercedes for Israel","The new covenant tablets","Sabbath and offerings","Building the tabernacle","The ark, table and lampstand","The altars and courtyard","The priestly garments completed","Glory fills the tabernacle"],
  es: ["Israel se multiplica en Egipto","El nacimiento de Moisés","La zarza ardiente","Moisés regresa a Egipto","El primer encuentro con Faraón","Dios reafirma la promesa","La primera plaga","Ranas, mosquitos y moscas","Plagas, úlceras y granizo","Langostas, tinieblas y anuncio de muerte","Se anuncia la última plaga","La Pascua y la salida de Egipto","Consagración de los primogénitos","El cruce del mar","El cántico de Moisés y Miriam","Maná y codornices","Agua de la roca y batalla contra Amalec","El consejo de Jetro","Israel llega al Sinaí","Los Diez Mandamientos","Leyes sobre siervos y violencia","Leyes sobre propiedad y justicia","Justicia, descanso y fiestas","La alianza es confirmada","Ofrendas para el santuario","El arca y el mobiliario","El altar y el atrio","Las vestiduras sacerdotales","La consagración de los sacerdotes","El altar del incienso y el rescate","Bezalel, el sábado y las tablas","El becerro de oro","Moisés intercede por Israel","Las nuevas tablas de la alianza","El sábado y las ofrendas","La construcción del tabernáculo","El arca, la mesa y el candelabro","Los altares y el atrio","Las vestiduras sacerdotales terminadas","La gloria llena el tabernáculo"],
  fr: ["Israël se multiplie en Égypte","La naissance de Moïse","Le buisson ardent","Moïse retourne en Égypte","La première rencontre avec Pharaon","Dieu réaffirme la promesse","La première plaie","Grenouilles, moustiques et mouches","Plaies, ulcères et grêle","Sauterelles, ténèbres et annonce de la mort","La dernière plaie annoncée","La Pâque et la sortie d'Égypte","Consécration des premiers-nés","La traversée de la mer","Le cantique de Moïse et Myriam","La manne et les cailles","L'eau du rocher et Amalec","Le conseil de Jéthro","Israël arrive au Sinaï","Les Dix Commandements","Lois sur les serviteurs et la violence","Lois sur les biens et la justice","Justice, repos et fêtes","L'alliance est confirmée","Offrandes pour le sanctuaire","L'arche et le mobilier","L'autel et le parvis","Les vêtements sacerdotaux","La consécration des prêtres","L'autel des parfums et la rançon","Betsaleel, le sabbat et les tables","Le veau d'or","Moïse intercède pour Israël","Les nouvelles tables de l'alliance","Le sabbat et les offrandes","La construction du tabernacle","L'arche, la table et le chandelier","Les autels et le parvis","Les vêtements sacerdotaux achevés","La gloire remplit le tabernacle"],
  it: ["Israele si moltiplica in Egitto","La nascita di Mosè","Il roveto ardente","Mosè ritorna in Egitto","Il primo incontro con il faraone","Dio riafferma la promessa","La prima piaga","Rane, zanzare e mosche","Piaghe, ulcere e grandine","Cavallette, tenebre e annuncio della morte","L'ultima piaga annunciata","La Pasqua e l'uscita dall'Egitto","Consacrazione dei primogeniti","Il passaggio del mare","Il canto di Mosè e Miriam","Manna e quaglie","Acqua dalla roccia e Amalec","Il consiglio di Ietro","Israele arriva al Sinai","I Dieci Comandamenti","Leggi sui servi e la violenza","Leggi sulla proprietà e la giustizia","Giustizia, riposo e feste","L'alleanza è confermata","Offerte per il santuario","L'arca e gli arredi","L'altare e il cortile","Le vesti sacerdotali","La consacrazione dei sacerdoti","L'altare dell'incenso e il riscatto","Besalel, il sabato e le tavole","Il vitello d'oro","Mosè intercede per Israele","Le nuove tavole dell'alleanza","Il sabato e le offerte","La costruzione del tabernacolo","L'arca, la tavola e il candelabro","Gli altari e il cortile","Le vesti sacerdotali completate","La gloria riempie il tabernacolo"],
  de: ["Israel wächst in Ägypten","Die Geburt Moses","Der brennende Dornbusch","Mose kehrt nach Ägypten zurück","Die erste Begegnung mit dem Pharao","Gott bekräftigt die Verheißung","Die erste Plage","Frösche, Mücken und Fliegen","Seuchen, Geschwüre und Hagel","Heuschrecken, Finsternis und Todesankündigung","Die letzte Plage wird angekündigt","Passah und Auszug aus Ägypten","Weihe der Erstgeborenen","Der Durchzug durch das Meer","Das Lied von Mose und Mirjam","Manna und Wachteln","Wasser aus dem Felsen und Amalek","Jitros Rat","Israel erreicht den Sinai","Die Zehn Gebote","Gesetze über Knechte und Gewalt","Gesetze über Eigentum und Gerechtigkeit","Gerechtigkeit, Ruhe und Feste","Der Bund wird bestätigt","Gaben für das Heiligtum","Die Lade und ihre Geräte","Der Altar und der Vorhof","Die priesterlichen Gewänder","Die Weihe der Priester","Räucheraltar und Lösegeld","Bezalel, Sabbat und Tafeln","Das goldene Kalb","Mose tritt für Israel ein","Die neuen Bundestafeln","Sabbat und Gaben","Der Bau der Stiftshütte","Lade, Tisch und Leuchter","Altäre und Vorhof","Die Priestergewänder werden vollendet","Die Herrlichkeit erfüllt die Stiftshütte"],
};

const prompts: Record<JourneyLanguage, string> = { "pt-PT": "Como este capítulo revela o poder, a presença ou a santidade de Deus?", en: "How does this chapter reveal God's power, presence or holiness?", es: "¿Cómo revela este capítulo el poder, la presencia o la santidad de Dios?", fr: "Comment ce chapitre révèle-t-il la puissance, la présence ou la sainteté de Dieu ?", it: "In che modo questo capitolo rivela la potenza, la presenza o la santità di Dio?", de: "Wie offenbart dieses Kapitel Gottes Macht, Gegenwart oder Heiligkeit?" };

export function buildExodusChapters(): JourneyChapter[] {
  return Array.from({ length: 40 }, (_, index) => { const number = index + 1; const sectionSlug = number <= 4 ? "deliverer" : number <= 12 ? "confrontation" : number <= 18 ? "deliverance" : number <= 24 ? "covenant" : "tabernacle"; const content = Object.fromEntries((Object.keys(titles) as JourneyLanguage[]).map(language => [language, { title: titles[language][index], description: titles[language][index], reflectionPrompt: prompts[language] }])) as JourneyChapter["content"]; return { number, sectionSlug, content }; });
}
