import type { JourneyChapter, JourneyLanguage } from "./types";
import { genesisEditorialPilot } from "./genesis-editorial-pilot";

const titles: Record<JourneyLanguage, string[]> = {
  fr: ["La création du monde","L'homme et le jardin d'Éden","La chute de l'humanité","Caïn et Abel","La descendance d'Adam","La corruption et l'appel de Noé","Le déluge","La fin du déluge","L'alliance avec Noé","La descendance de Noé","La tour de Babel","L'appel d'Abram","Abram et Lot se séparent","Abram sauve Lot","L'alliance avec Abram","La naissance d'Ismaël","L'alliance de la circoncision","La promesse de la naissance d'Isaac","Sodome et Gomorrhe","Abraham et Abimélek","La naissance d'Isaac","Le sacrifice d'Isaac","La mort de Sara","Le mariage d'Isaac et Rébecca","La mort d'Abraham","Isaac à Guérar","Jacob reçoit la bénédiction","Le songe de Jacob à Béthel","Jacob épouse Léa et Rachel","Les fils de Jacob","Jacob fuit Laban","Jacob lutte avec l'Ange","Jacob retrouve Ésaü","Dina et les Sicémites","Retour à Béthel","La descendance d'Ésaü","Joseph vendu par ses frères","Juda et Tamar","Joseph chez Potiphar","Les rêves des prisonniers","Le rêve de Pharaon","Les frères de Joseph en Égypte","Le second voyage en Égypte","La coupe de Joseph","Joseph se révèle à ses frères","La famille de Jacob en Égypte","Joseph administre l'Égypte","Jacob bénit les fils de Joseph","Jacob bénit ses fils","La mort de Jacob et Joseph"],
  "pt-PT": ["A criação do mundo","O homem e o jardim do Éden","A queda da humanidade","Caim e Abel","A descendência de Adão","A corrupção e o chamado de Noé","O dilúvio","O fim do dilúvio","A aliança com Noé","A descendência de Noé","A torre de Babel","O chamado de Abrão","Abrão e Ló separam-se","Abrão salva Ló","A aliança com Abrão","O nascimento de Ismael","A aliança da circuncisão","A promessa do nascimento de Isaac","Sodoma e Gomorra","Abraão e Abimeleque","O nascimento de Isaac","O sacrifício de Isaac","A morte de Sara","O casamento de Isaac e Rebeca","A morte de Abraão","Isaac em Gerar","Jacob recebe a bênção","O sonho de Jacob em Betel","Jacob casa com Lia e Raquel","Os filhos de Jacob","Jacob foge de Labão","Jacob luta com o Anjo","Jacob reencontra Esaú","Diná e os siquemitas","O regresso a Betel","A descendência de Esaú","José é vendido pelos irmãos","Judá e Tamar","José na casa de Potifar","Os sonhos dos prisioneiros","O sonho do Faraó","Os irmãos de José no Egito","A segunda viagem ao Egito","A taça de José","José revela-se aos irmãos","A família de Jacob no Egito","José administra o Egito","Jacob abençoa os filhos de José","Jacob abençoa os seus filhos","A morte de Jacob e José"],
  en: ["The creation of the world","Humanity and the garden of Eden","The fall of humanity","Cain and Abel","The descendants of Adam","Corruption and the call of Noah","The flood","The end of the flood","The covenant with Noah","The descendants of Noah","The tower of Babel","The call of Abram","Abram and Lot separate","Abram rescues Lot","The covenant with Abram","The birth of Ishmael","The covenant of circumcision","The promise of Isaac's birth","Sodom and Gomorrah","Abraham and Abimelech","The birth of Isaac","The sacrifice of Isaac","The death of Sarah","Isaac and Rebekah's marriage","The death of Abraham","Isaac in Gerar","Jacob receives the blessing","Jacob's dream at Bethel","Jacob marries Leah and Rachel","The sons of Jacob","Jacob flees from Laban","Jacob wrestles with the Angel","Jacob meets Esau","Dinah and the Shechemites","The return to Bethel","The descendants of Esau","Joseph is sold by his brothers","Judah and Tamar","Joseph in Potiphar's house","The prisoners' dreams","Pharaoh's dream","Joseph's brothers in Egypt","The second journey to Egypt","Joseph's cup","Joseph reveals himself","Jacob's family in Egypt","Joseph administers Egypt","Jacob blesses Joseph's sons","Jacob blesses his sons","The death of Jacob and Joseph"],
  es: ["La creación del mundo","El ser humano y el jardín del Edén","La caída de la humanidad","Caín y Abel","La descendencia de Adán","La corrupción y el llamado de Noé","El diluvio","El fin del diluvio","El pacto con Noé","La descendencia de Noé","La torre de Babel","El llamado de Abram","Abram y Lot se separan","Abram rescata a Lot","El pacto con Abram","El nacimiento de Ismael","El pacto de la circuncisión","La promesa del nacimiento de Isaac","Sodoma y Gomorra","Abraham y Abimelec","El nacimiento de Isaac","El sacrificio de Isaac","La muerte de Sara","El matrimonio de Isaac y Rebeca","La muerte de Abraham","Isaac en Gerar","Jacob recibe la bendición","El sueño de Jacob en Betel","Jacob se casa con Lea y Raquel","Los hijos de Jacob","Jacob huye de Labán","Jacob lucha con el Ángel","Jacob se encuentra con Esaú","Dina y los siquemitas","El regreso a Betel","La descendencia de Esaú","José es vendido por sus hermanos","Judá y Tamar","José en casa de Potifar","Los sueños de los prisioneros","El sueño del faraón","Los hermanos de José en Egipto","El segundo viaje a Egipto","La copa de José","José se revela a sus hermanos","La familia de Jacob en Egipto","José administra Egipto","Jacob bendice a los hijos de José","Jacob bendice a sus hijos","La muerte de Jacob y José"],
  it: ["La creazione del mondo","L'umanità e il giardino dell'Eden","La caduta dell'umanità","Caino e Abele","La discendenza di Adamo","La corruzione e la chiamata di Noè","Il diluvio","La fine del diluvio","L'alleanza con Noè","La discendenza di Noè","La torre di Babele","La chiamata di Abramo","Abramo e Lot si separano","Abramo salva Lot","L'alleanza con Abramo","La nascita di Ismaele","L'alleanza della circoncisione","La promessa della nascita di Isacco","Sodoma e Gomorra","Abramo e Abimelec","La nascita di Isacco","Il sacrificio di Isacco","La morte di Sara","Il matrimonio di Isacco e Rebecca","La morte di Abramo","Isacco a Gherar","Giacobbe riceve la benedizione","Il sogno di Giacobbe a Betel","Giacobbe sposa Lia e Rachele","I figli di Giacobbe","Giacobbe fugge da Labano","Giacobbe lotta con l'Angelo","Giacobbe incontra Esaù","Dina e i Sichemiti","Il ritorno a Betel","La discendenza di Esaù","Giuseppe venduto dai fratelli","Giuda e Tamar","Giuseppe nella casa di Potifar","I sogni dei prigionieri","Il sogno del faraone","I fratelli di Giuseppe in Egitto","Il secondo viaggio in Egitto","La coppa di Giuseppe","Giuseppe si rivela ai fratelli","La famiglia di Giacobbe in Egitto","Giuseppe amministra l'Egitto","Giacobbe benedice i figli di Giuseppe","Giacobbe benedice i suoi figli","La morte di Giacobbe e Giuseppe"],
  de: ["Die Schöpfung der Welt","Der Mensch und der Garten Eden","Der Sündenfall","Kain und Abel","Die Nachkommen Adams","Die Verderbnis und Noahs Berufung","Die Sintflut","Das Ende der Sintflut","Der Bund mit Noah","Die Nachkommen Noahs","Der Turmbau zu Babel","Die Berufung Abrams","Abram und Lot trennen sich","Abram rettet Lot","Der Bund mit Abram","Die Geburt Ismaels","Der Bund der Beschneidung","Die Verheißung von Isaaks Geburt","Sodom und Gomorra","Abraham und Abimelech","Die Geburt Isaaks","Die Opferung Isaaks","Der Tod Saras","Isaak und Rebekkas Hochzeit","Der Tod Abrahams","Isaak in Gerar","Jakob erhält den Segen","Jakobs Traum in Bethel","Jakob heiratet Lea und Rahel","Die Söhne Jakobs","Jakob flieht vor Laban","Jakob ringt mit dem Engel","Jakob begegnet Esau","Dina und die Sichemiter","Die Rückkehr nach Bethel","Die Nachkommen Esaus","Josef wird von seinen Brüdern verkauft","Juda und Tamar","Josef im Haus Potifars","Die Träume der Gefangenen","Der Traum des Pharao","Josefs Brüder in Ägypten","Die zweite Reise nach Ägypten","Josefs Becher","Josef gibt sich seinen Brüdern zu erkennen","Jakobs Familie in Ägypten","Josef verwaltet Ägypten","Jakob segnet Josefs Söhne","Jakob segnet seine Söhne","Der Tod Jakobs und Josefs"],
};

const descriptions: Record<JourneyLanguage, (title: string) => string> = {
  "pt-PT": title => `Visão geral de ${title.toLowerCase()} e do seu lugar na história de Génesis.`,
  en: title => `An overview of ${title.toLowerCase()} and its place in the story of Genesis.`,
  es: title => `Una visión general de ${title.toLowerCase()} y su lugar en la historia de Génesis.`,
  fr: title => `Un aperçu de ${title.toLowerCase()} et de sa place dans l'histoire de la Genèse.`,
  it: title => `Una panoramica di ${title.toLowerCase()} e del suo posto nella storia della Genesi.`,
  de: title => `Ein Überblick über „${title}“ und seine Bedeutung in der Genesis-Erzählung.`,
};

const prompts: Record<JourneyLanguage, string> = {
  "pt-PT": "O que este capítulo revela sobre Deus, a humanidade e a tua resposta de fé?", en: "What does this chapter reveal about God, humanity and your response of faith?", es: "¿Qué revela este capítulo sobre Dios, la humanidad y tu respuesta de fe?", fr: "Que révèle ce chapitre sur Dieu, l'humanité et votre réponse de foi ?", it: "Che cosa rivela questo capitolo su Dio, sull'umanità e sulla tua risposta di fede?", de: "Was offenbart dieses Kapitel über Gott, die Menschheit und deine Antwort des Glaubens?",
};

export function buildGenesisChapters(): JourneyChapter[] {
  return Array.from({ length: 50 }, (_, index) => {
    const number = index + 1;
    const sectionSlug = number <= 2 ? "creation" : number === 3 ? "fall" : number <= 5 ? "first-generations" : number <= 9 ? "flood" : number <= 11 ? "nations" : "patriarchs";
    const content = Object.fromEntries((Object.keys(titles) as JourneyLanguage[]).map(language => {
      const title = titles[language][index];
      const pilot = genesisEditorialPilot[number]?.[language];
      return [language, { title, description: pilot?.description ?? descriptions[language](title), reflectionPrompt: pilot?.reflectionPrompt ?? prompts[language], editorial: pilot?.editorial }];
    })) as JourneyChapter["content"];
    return { number, sectionSlug, content };
  });
}
