import type { JourneyChapterEditorial, JourneyLanguage } from "./types";
type PilotContent = { description: string; reflectionPrompt: string; editorial: JourneyChapterEditorial };
const langs:JourneyLanguage[]=["pt-PT","en","es","fr","it","de"];
const localized=(description:string[],reflection:string[],theme:string[],characters:string[][],places:string[][],previous:string[],next:string[],refs:string[]):Record<JourneyLanguage,PilotContent>=>Object.fromEntries(langs.map((language,index)=>[language,{description:description[index],reflectionPrompt:reflection[index],editorial:{keyTheme:theme[index],characters:characters[index],places:places[index],relatedReferences:refs,previousConnection:previous[index],nextConnection:next[index]}}])) as Record<JourneyLanguage,PilotContent>;

export const genesisEditorialPilot:Record<number,Record<JourneyLanguage,PilotContent>>={
  1:localized(
    ["Deus cria e ordena os céus, a terra e todos os seres vivos. A humanidade é criada à imagem de Deus e recebe a responsabilidade de cuidar da criação.","God creates and orders the heavens, earth and every living creature. Humanity is made in God's image and entrusted with the care of creation.","Dios crea y ordena los cielos, la tierra y todos los seres vivos. La humanidad es creada a imagen de Dios y recibe el cuidado de la creación.","Dieu crée et ordonne les cieux, la terre et tous les êtres vivants. L'humanité est créée à son image et reçoit la responsabilité de prendre soin de la création.","Dio crea e ordina i cieli, la terra e ogni essere vivente. L'umanità è creata a sua immagine e riceve la cura del creato.","Gott schafft und ordnet Himmel, Erde und alle Lebewesen. Der Mensch wird als Gottes Ebenbild geschaffen und mit der Bewahrung der Schöpfung betraut."],
    ["Como viverás hoje como imagem de Deus e cuidador da sua criação?","How will you live today as God's image-bearer and steward of creation?","¿Cómo vivirás hoy como imagen de Dios y cuidador de su creación?","Comment vivrez-vous aujourd'hui comme image de Dieu et gardien de sa création ?","Come vivrai oggi come immagine di Dio e custode del creato?","Wie wirst du heute als Gottes Ebenbild und Bewahrer der Schöpfung leben?"],
    ["Criação, ordem e imagem de Deus","Creation, order and image of God","Creación, orden e imagen de Dios","Création, ordre et image de Dieu","Creazione, ordine e immagine di Dio","Schöpfung, Ordnung und Gottes Ebenbild"],
    langs.map((_,i)=>[["Deus","Humanidade"],["God","Humanity"],["Dios","Humanidad"],["Dieu","Humanité"],["Dio","Umanità"],["Gott","Menschheit"]][i]),langs.map((_,i)=>[["Mundo criado"],["Created world"],["Mundo creado"],["Monde créé"],["Mondo creato"],["Geschaffene Welt"]][i]),
    ["Aqui começa a história bíblica.","The biblical story begins here.","Aquí comienza la historia bíblica.","L'histoire biblique commence ici.","Qui inizia la storia biblica.","Hier beginnt die biblische Geschichte."],
    ["O capítulo seguinte aproxima o olhar para a humanidade e o jardim.","The next chapter focuses on humanity and the garden.","El capítulo siguiente enfoca a la humanidad y el jardín.","Le chapitre suivant se concentre sur l'humanité et le jardin.","Il capitolo seguente si concentra sull'umanità e sul giardino.","Das nächste Kapitel richtet den Blick auf Mensch und Garten."],["João 1:1-3","Colossenses 1:16-17","Hebreus 11:3"]),
  2:localized(
    ["Deus conclui a criação com o descanso do sétimo dia, coloca o homem no Éden e estabelece a união entre homem e mulher. Trabalho, limites, comunhão e casamento aparecem como dons da criação.","God completes creation with seventh-day rest, places the man in Eden and establishes the union of man and woman. Work, limits, fellowship and marriage appear as gifts of creation.","Dios completa la creación con el descanso del séptimo día, coloca al hombre en Edén y establece la unión entre hombre y mujer. Trabajo, límites, comunión y matrimonio aparecen como dones.","Dieu achève la création par le repos du septième jour, place l'homme en Éden et établit l'union de l'homme et de la femme. Travail, limites, communion et mariage sont présentés comme des dons.","Dio completa la creazione con il riposo del settimo giorno, pone l'uomo in Eden e stabilisce l'unione tra uomo e donna. Lavoro, limiti, comunione e matrimonio sono doni.","Gott vollendet die Schöpfung mit der Ruhe des siebten Tages, setzt den Menschen in Eden ein und stiftet die Verbindung von Mann und Frau. Arbeit, Grenzen, Gemeinschaft und Ehe erscheinen als Gaben."],
    ["Como podes receber o trabalho, o descanso e as relações como dons de Deus?","How can you receive work, rest and relationships as gifts from God?","¿Cómo puedes recibir el trabajo, el descanso y las relaciones como dones de Dios?","Comment recevoir le travail, le repos et les relations comme des dons de Dieu ?","Come puoi accogliere lavoro, riposo e relazioni come doni di Dio?","Wie kannst du Arbeit, Ruhe und Beziehungen als Gaben Gottes annehmen?"],
    ["Descanso, vocação, limites e aliança","Rest, vocation, boundaries and covenant","Descanso, vocación, límites y pacto","Repos, vocation, limites et alliance","Riposo, vocazione, limiti e alleanza","Ruhe, Berufung, Grenzen und Bund"],
    langs.map((_,i)=>[["Deus","Adão","Eva"],["God","Adam","Eve"],["Dios","Adán","Eva"],["Dieu","Adam","Ève"],["Dio","Adamo","Eva"],["Gott","Adam","Eva"]][i]),langs.map((_,i)=>[["Jardim do Éden"],["Garden of Eden"],["Jardín del Edén"],["Jardin d'Éden"],["Giardino dell'Eden"],["Garten Eden"]][i]),
    ["A narrativa amplia o sexto dia da criação.","The narrative expands the sixth day of creation.","La narración amplía el sexto día de la creación.","Le récit développe le sixième jour de la création.","Il racconto approfondisce il sesto giorno della creazione.","Die Erzählung vertieft den sechsten Schöpfungstag."],
    ["A confiança e os limites estabelecidos no jardim serão postos à prova.","Trust and the boundaries set in the garden will be tested.","La confianza y los límites del jardín serán puestos a prueba.","La confiance et les limites du jardin seront mises à l'épreuve.","La fiducia e i limiti del giardino saranno messi alla prova.","Vertrauen und Grenzen im Garten werden auf die Probe gestellt."],["Marcos 2:27","Mateus 19:4-6","Efésios 5:31-32"]),
  3:localized(
    ["A serpente distorce a palavra de Deus, e o homem e a mulher ultrapassam o limite estabelecido. Vergonha, conflito e morte entram na experiência humana, mas Deus procura os culpados e anuncia a primeira esperança de vitória sobre o mal.","The serpent distorts God's word, and the man and woman cross the given boundary. Shame, conflict and death enter human experience, yet God seeks the guilty and announces the first hope of victory over evil.","La serpiente distorsiona la palabra de Dios y el hombre y la mujer traspasan el límite. Vergüenza, conflicto y muerte entran en la experiencia humana, pero Dios busca a los culpables y anuncia esperanza sobre el mal.","Le serpent déforme la parole de Dieu et l'homme et la femme franchissent la limite. Honte, conflit et mort entrent dans l'expérience humaine, mais Dieu cherche les coupables et annonce l'espérance d'une victoire sur le mal.","Il serpente distorce la parola di Dio e l'uomo e la donna oltrepassano il limite. Vergogna, conflitto e morte entrano nell'esperienza umana, ma Dio cerca i colpevoli e annuncia speranza contro il male.","Die Schlange verdreht Gottes Wort, und Mann und Frau überschreiten die gesetzte Grenze. Scham, Konflikt und Tod treten in die menschliche Erfahrung, doch Gott sucht die Schuldigen und kündigt Hoffnung auf den Sieg über das Böse an."],
    ["Onde precisas abandonar desculpas, confessar o pecado e confiar na graça de Deus?","Where do you need to abandon excuses, confess sin and trust God's grace?","¿Dónde necesitas dejar las excusas, confesar el pecado y confiar en la gracia de Dios?","Où devez-vous abandonner les excuses, confesser le péché et faire confiance à la grâce de Dieu ?","Dove devi abbandonare le scuse, confessare il peccato e confidare nella grazia di Dio?","Wo musst du Ausreden aufgeben, Sünde bekennen und Gottes Gnade vertrauen?"],
    ["Queda, consequências e primeira promessa","Fall, consequences and first promise","Caída, consecuencias y primera promesa","Chute, conséquences et première promesse","Caduta, conseguenze e prima promessa","Sündenfall, Folgen und erste Verheißung"],
    langs.map((_,i)=>[["Deus","Adão","Eva","Serpente"],["God","Adam","Eve","Serpent"],["Dios","Adán","Eva","Serpiente"],["Dieu","Adam","Ève","Serpent"],["Dio","Adamo","Eva","Serpente"],["Gott","Adam","Eva","Schlange"]][i]),langs.map((_,i)=>[["Jardim do Éden"],["Garden of Eden"],["Jardín del Edén"],["Jardin d'Éden"],["Giardino dell'Eden"],["Garten Eden"]][i]),
    ["Os dons e limites do Éden são rejeitados pela desobediência.","The gifts and boundaries of Eden are rejected through disobedience.","Los dones y límites del Edén son rechazados por la desobediencia.","Les dons et les limites d'Éden sont rejetés par la désobéissance.","I doni e i limiti dell'Eden sono rifiutati con la disobbedienza.","Gaben und Grenzen Edens werden durch Ungehorsam verworfen."],
    ["No capítulo seguinte, o pecado espalha-se para a relação entre irmãos.","In the next chapter, sin spreads into the relationship between brothers.","En el capítulo siguiente, el pecado se extiende a la relación entre hermanos.","Au chapitre suivant, le péché atteint la relation entre frères.","Nel capitolo seguente il peccato si estende al rapporto tra fratelli.","Im nächsten Kapitel greift die Sünde auf die Beziehung zwischen Brüdern über."],["Romanos 5:12-19","1 Coríntios 15:21-22","Apocalipse 12:9"]),
};
