import type { JourneyBook, JourneyLanguage, JourneySection } from "./types";
const langs: JourneyLanguage[] = ["pt-PT", "en", "es", "fr", "it", "de"];
const l = <T>(v:T[]) => Object.fromEntries(langs.map((x,i)=>[x,v[i]])) as Record<JourneyLanguage,T>;
const names=l(["Josué","Joshua","Josué","Josué","Giosuè","Josua"]), descriptions=l(["Israel entra em Canaã pela fé e obediência.","Israel enters Canaan by faith and obedience.","Israel entra en Canaán por fe y obediencia.","Israël entre en Canaan par la foi et l'obéissance.","Israele entra in Canaan per fede e obbedienza.","Israel zieht durch Glauben und Gehorsam nach Kanaan ein."]), prompts=l(["Onde Deus te chama a avançar com coragem?","Where is God calling you to move forward courageously?","¿Dónde te llama Dios a avanzar con valor?","Où Dieu vous appelle-t-il à avancer avec courage ?","Dove Dio ti chiama ad avanzare con coraggio?","Wo ruft Gott dich, mutig voranzugehen?"]);
const rows=[ ["commission",1,5,["Preparação para Canaã","Preparation for Canaan","Preparación para Canaán","Préparation pour Canaan","Preparazione per Canaan","Vorbereitung auf Kanaan"]], ["conquest",6,12,["Conquista da terra","Conquest of the land","Conquista de la tierra","Conquête du pays","Conquista della terra","Eroberung des Landes"]], ["inheritance",13,21,["Distribuição da herança","Distribution of the inheritance","Distribución de la herencia","Partage de l'héritage","Distribuzione dell'eredità","Verteilung des Erbes"]], ["renewal",22,24,["Renovação da aliança","Covenant renewal","Renovación del pacto","Renouvellement de l'alliance","Rinnovo dell'alleanza","Erneuerung des Bundes"]] ] as const;
const sections:JourneySection[]=rows.map(([slug,startChapter,endChapter,titles])=>({slug,startChapter,endChapter,icon:"shield",content:Object.fromEntries(langs.map((x,i)=>[x,{title:titles[i],description:descriptions[x]}])) as JourneySection["content"]}));
const authors=l(["Tradicionalmente atribuído a Josué","Traditionally attributed to Joshua","Tradicionalmente atribuido a Josué","Traditionnellement attribué à Josué","Tradizionalmente attribuito a Giosuè","Traditionell Josua zugeschrieben"]), origins=l(["O Senhor salva.","The Lord saves.","El Señor salva.","Le Seigneur sauve.","Il Signore salva.","Der Herr rettet."]), themes=l([["Coragem","Promessa","Obediência"],["Courage","Promise","Obedience"],["Valor","Promesa","Obediencia"],["Courage","Promesse","Obéissance"],["Coraggio","Promessa","Obbedienza"],["Mut","Verheißung","Gehorsam"]]), characters=l([["Josué","Raabe","Caleb"],["Joshua","Rahab","Caleb"],["Josué","Rahab","Caleb"],["Josué","Rahab","Caleb"],["Giosuè","Raab","Caleb"],["Josua","Rahab","Kaleb"]]);
export const joshua:JourneyBook={slug:"joshua",testament:"old-testament",category:"historical",bibleBookId:6,chapterCount:24,position:6,coverKey:"joshua",overview:Object.fromEntries(langs.map(x=>[x,{title:names[x],description:descriptions[x],author:authors[x],date:"c. 1400-1370",nameOrigin:origins[x],context:descriptions[x],themes:themes[x],characters:characters[x],principles:[prompts[x]]}])) as JourneyBook["overview"],sections,chapters:Array.from({length:24},(_,i)=>{const number=i+1,s=sections.find(v=>number>=v.startChapter&&number<=v.endChapter)!;return{number,sectionSlug:s.slug,content:Object.fromEntries(langs.map(x=>[x,{title:`${s.content[x].title} · ${number}`,description:descriptions[x],reflectionPrompt:prompts[x]}])) as JourneyBook["chapters"][number]["content"]}})};

export const historicalCategoryLabels = l(["Livros históricos", "Historical books", "Libros históricos", "Livres historiques", "Libri storici", "Geschichtsbücher"]);
