import { commonUnknownAuthors, createJourneyBook, journeyLocalized, type JourneyBookStage, type LocalizedValues } from "./book-factory";
import type { JourneyBook, JourneyLanguage } from "./types";
const langs:JourneyLanguage[]=["pt-PT","en","es","fr","it","de"], n=(...v:string[])=>v as LocalizedValues<string>;
type StageKey="call"|"warning"|"judgment"|"mission"|"prayer"|"visions"|"hope"|"restoration";
const stageTitles:Record<StageKey,LocalizedValues<string>>={
 call:n("Chamado e contexto","Call and context","Llamado y contexto","Appel et contexte","Chiamata e contesto","Berufung und Kontext"),warning:n("Advertência e arrependimento","Warning and repentance","Advertencia y arrepentimiento","Avertissement et repentance","Avvertimento e pentimento","Warnung und Umkehr"),judgment:n("O dia do juízo","The day of judgment","El día del juicio","Le jour du jugement","Il giorno del giudizio","Der Tag des Gerichts"),mission:n("A missão profética","The prophetic mission","La misión profética","La mission prophétique","La missione profetica","Die prophetische Mission"),prayer:n("Oração e encontro com Deus","Prayer and encounter with God","Oración y encuentro con Dios","Prière et rencontre avec Dieu","Preghiera e incontro con Dio","Gebet und Begegnung mit Gott"),visions:n("Visões e sinais","Visions and signs","Visiones y señales","Visions et signes","Visioni e segni","Visionen und Zeichen"),hope:n("Promessa e esperança","Promise and hope","Promesa y esperanza","Promesse et espérance","Promessa e speranza","Verheißung und Hoffnung"),restoration:n("Restauração e fidelidade","Restoration and faithfulness","Restauración y fidelidad","Restauration et fidélité","Restaurazione e fedeltà","Wiederherstellung und Treue")};
const prompts=n("Como responderás ao chamado de Deus para arrependimento e fidelidade?","How will you respond to God's call to repentance and faithfulness?","¿Cómo responderás al llamado de Dios al arrepentimiento y la fidelidad?","Comment répondrez-vous à l'appel de Dieu à la repentance et à la fidélité ?","Come risponderai alla chiamata di Dio al pentimento e alla fedeltà?","Wie antwortest du auf Gottes Ruf zu Umkehr und Treue?");
const themes=n(["Arrependimento","Justiça","Esperança"],["Repentance","Justice","Hope"],["Arrepentimiento","Justicia","Esperanza"],["Repentance","Justice","Espérance"],["Pentimento","Giustizia","Speranza"],["Umkehr","Gerechtigkeit","Hoffnung"]);
const origins=n("O livro recebe o nome do profeta que transmite a mensagem.","The book is named after the prophet who delivers its message.","El libro recibe el nombre del profeta que transmite el mensaje.","Le livre porte le nom du prophète qui transmet le message.","Il libro prende il nome dal profeta che trasmette il messaggio.","Das Buch trägt den Namen des Propheten, der die Botschaft überbringt.");
type StageSpec=[StageKey,number,number];
function prophet(slug:string,id:number,count:number,names:LocalizedValues<string>,focus:LocalizedValues<string>,specs:StageSpec[]):JourneyBook{
 const localizedNames=journeyLocalized(names),localizedFocus=journeyLocalized(focus);
 const descriptions=langs.map(language=>`${localizedNames[language]} — ${localizedFocus[language]}`) as LocalizedValues<string>;
 const stages:JourneyBookStage[]=specs.map(([key,start,end])=>({slug:key,start,end,titles:stageTitles[key],icon:"flame"}));
 const characters=langs.map(language=>[localizedNames[language]]) as LocalizedValues<string[]>;
 return createJourneyBook({slug,bibleBookId:id,chapterCount:count,position:id,category:"minor_prophet",names,descriptions,prompts,authors:commonUnknownAuthors,origins,themes,characters,date:"c. 800-430 a.C.",stages});
}
export const hosea=prophet("hosea",28,14,n("Oseias","Hosea","Oseas","Osée","Osea","Hosea"),n("amor fiel de Deus por um povo infiel.","God's faithful love for an unfaithful people.","amor fiel de Dios por un pueblo infiel.","amour fidèle de Dieu pour un peuple infidèle.","amore fedele di Dio per un popolo infedele.","Gottes treue Liebe zu einem untreuen Volk."),[["call",1,3],["warning",4,10],["restoration",11,14]]);
export const joel=prophet("joel",29,3,n("Joel","Joel","Joel","Joël","Gioele","Joel"),n("o dia do Senhor, arrependimento e derramamento do Espírito.","the day of the Lord, repentance and outpouring of the Spirit.","el día del Señor, arrepentimiento y derramamiento del Espíritu.","le jour du Seigneur, la repentance et l'effusion de l'Esprit.","il giorno del Signore, pentimento ed effusione dello Spirito.","Tag des Herrn, Umkehr und Ausgießung des Geistes."),[["warning",1,1],["hope",2,2],["judgment",3,3]]);
export const amos=prophet("amos",30,9,n("Amós","Amos","Amós","Amos","Amos","Amos"),n("justiça para os oprimidos e responsabilidade diante da aliança.","justice for the oppressed and covenant accountability.","justicia para los oprimidos y responsabilidad ante el pacto.","justice pour les opprimés et responsabilité envers l'alliance.","giustizia per gli oppressi e responsabilità nell'alleanza.","Gerechtigkeit für Unterdrückte und Verantwortung im Bund."),[["judgment",1,2],["warning",3,6],["visions",7,9]]);
export const obadiah=prophet("obadiah",31,1,n("Obadias","Obadiah","Abdías","Abdias","Abdia","Obadja"),n("a queda do orgulho de Edom e o reino do Senhor.","the fall of Edom's pride and the Lord's kingdom.","la caída del orgullo de Edom y el reino del Señor.","la chute de l'orgueil d'Édom et le règne du Seigneur.","la caduta dell'orgoglio di Edom e il regno del Signore.","Fall von Edoms Stolz und Herrschaft des Herrn."),[["judgment",1,1]]);
export const jonah=prophet("jonah",32,4,n("Jonas","Jonah","Jonás","Jonas","Giona","Jona"),n("a misericórdia de Deus alcança Nínive e confronta o coração do profeta.","God's mercy reaches Nineveh and confronts the prophet's heart.","la misericordia de Dios alcanza Nínive y confronta el corazón del profeta.","la miséricorde de Dieu atteint Ninive et confronte le cœur du prophète.","la misericordia di Dio raggiunge Ninive e affronta il cuore del profeta.","Gottes Barmherzigkeit erreicht Ninive und stellt das Herz des Propheten infrage."),[["mission",1,1],["prayer",2,2],["restoration",3,3],["warning",4,4]]);
export const micah=prophet("micah",33,7,n("Miqueias","Micah","Miqueas","Michée","Michea","Micha"),n("juízo, justiça, o governante de Belém e esperança restauradora.","judgment, justice, the ruler from Bethlehem and restoring hope.","juicio, justicia, el gobernante de Belén y esperanza restauradora.","jugement, justice, le chef de Bethléem et espérance restauratrice.","giudizio, giustizia, il sovrano di Betlemme e speranza restauratrice.","Gericht, Gerechtigkeit, Herrscher aus Bethlehem und erneuernde Hoffnung."),[["judgment",1,3],["hope",4,5],["restoration",6,7]]);
export const nahum=prophet("nahum",34,3,n("Naum","Nahum","Nahúm","Nahum","Naum","Nahum"),n("a queda de Nínive e a justiça soberana de Deus.","Nineveh's fall and God's sovereign justice.","la caída de Nínive y la justicia soberana de Dios.","la chute de Ninive et la justice souveraine de Dieu.","la caduta di Ninive e la giustizia sovrana di Dio.","Ninives Fall und Gottes souveräne Gerechtigkeit."),[["hope",1,1],["judgment",2,3]]);
export const habakkuk=prophet("habakkuk",35,3,n("Habacuque","Habakkuk","Habacuc","Habacuc","Abacuc","Habakuk"),n("perguntas honestas amadurecem numa fé que se alegra em Deus.","honest questions mature into faith that rejoices in God.","preguntas honestas maduran en una fe que se alegra en Dios.","des questions honnêtes mûrissent en une foi qui se réjouit en Dieu.","domande sincere maturano in una fede che gioisce in Dio.","ehrliche Fragen reifen zu einem Glauben, der sich an Gott freut."),[["prayer",1,2],["hope",3,3]]);
export const zephaniah=prophet("zephaniah",36,3,n("Sofonias","Zephaniah","Sofonías","Sophonie","Sofonia","Zefanja"),n("o dia do Senhor purifica e conduz um povo humilde à alegria.","the day of the Lord purifies and leads a humble people to joy.","el día del Señor purifica y conduce a un pueblo humilde a la alegría.","le jour du Seigneur purifie et conduit un peuple humble à la joie.","il giorno del Signore purifica e conduce un popolo umile alla gioia.","Tag des Herrn reinigt und führt ein demütiges Volk zur Freude."),[["judgment",1,2],["restoration",3,3]]);
export const haggai=prophet("haggai",37,2,n("Ageu","Haggai","Hageo","Aggée","Aggeo","Haggai"),n("o povo retoma a construção do templo e reorganiza as prioridades.","the people resume building the temple and reorder their priorities.","el pueblo retoma la construcción del templo y reorganiza sus prioridades.","le peuple reprend la construction du temple et réordonne ses priorités.","il popolo riprende la costruzione del tempio e riordina le priorità.","Volk nimmt den Tempelbau wieder auf und ordnet seine Prioritäten neu."),[["call",1,1],["hope",2,2]]);
export const zechariah=prophet("zechariah",38,14,n("Zacarias","Zechariah","Zacarías","Zacharie","Zaccaria","Sacharja"),n("visões de restauração apontam para o Rei humilde e o reino futuro.","visions of restoration point to the humble King and future kingdom.","visiones de restauración apuntan al Rey humilde y al reino futuro.","des visions de restauration désignent le Roi humble et le royaume futur.","visioni di restaurazione indicano il Re umile e il regno futuro.","Visionen der Wiederherstellung weisen auf den demütigen König und das künftige Reich."),[["visions",1,6],["warning",7,8],["hope",9,14]]);
export const malachi=prophet("malachi",39,4,n("Malaquias","Malachi","Malaquías","Malachie","Malachia","Maleachi"),n("Deus confronta um culto sem coração e promete preparar o caminho.","God confronts heartless worship and promises to prepare the way.","Dios confronta un culto sin corazón y promete preparar el camino.","Dieu confronte un culte sans cœur et promet de préparer le chemin.","Dio affronta un culto senza cuore e promette di preparare la via.","Gott stellt herzlosen Gottesdienst bloß und verheißt, den Weg zu bereiten."),[["warning",1,3],["hope",4,4]]);
export const minorProphets=[hosea,joel,amos,obadiah,jonah,micah,nahum,habakkuk,zephaniah,haggai,zechariah,malachi];
