import { commonUnknownAuthors, createJourneyBook, journeyLocalized, type JourneyBookStage, type LocalizedValues } from "./book-factory";
import type { JourneyBook } from "./types";

const prompts: LocalizedValues<string> = ["Como Deus te chama a regressar, reconstruir e permanecer fiel?", "How is God calling you to return, rebuild and remain faithful?", "¿Cómo te llama Dios a regresar, reconstruir y permanecer fiel?", "Comment Dieu vous appelle-t-il à revenir, reconstruire et rester fidèle ?", "In che modo Dio ti chiama a tornare, ricostruire e rimanere fedele?", "Wie ruft Gott dich zur Rückkehr, zum Wiederaufbau und zur Treue?"];
const themes: LocalizedValues<string[]> = [["Aliança","Reforma","Restauração"],["Covenant","Reform","Restoration"],["Pacto","Reforma","Restauración"],["Alliance","Réforme","Restauration"],["Alleanza","Riforma","Restaurazione"],["Bund","Reform","Wiederherstellung"]];
const origins: LocalizedValues<string> = ["O nome identifica o livro e a sua personagem ou período central.","The name identifies the book and its central person or period.","El nombre identifica el libro y su personaje o período central.","Le nom identifie le livre et son personnage ou sa période centrale.","Il nome identifica il libro e il suo personaggio o periodo centrale.","Der Name bezeichnet das Buch und seine zentrale Person oder Zeit."];
const names = (...values:string[]) => values as LocalizedValues<string>;
const stage = (slug:string,start:number,end:number,...titles:string[]):JourneyBookStage => ({slug,start,end,titles:titles as LocalizedValues<string>});
const chars = (...values:string[][]) => values as LocalizedValues<string[]>;

function book(slug:string,id:number,count:number,bookNames:LocalizedValues<string>,descriptions:LocalizedValues<string>,characters:LocalizedValues<string[]>,stages:JourneyBookStage[]):JourneyBook {
  return createJourneyBook({slug,bibleBookId:id,chapterCount:count,position:id,category:"historical",names:bookNames,descriptions,prompts,authors:commonUnknownAuthors,origins,themes,characters,date:"c. 970-400 a.C.",stages});
}

export const secondChronicles = book("2-chronicles",14,36,names("2 Crónicas","2 Chronicles","2 Crónicas","2 Chroniques","2 Cronache","2 Chronik"),names("Do templo de Salomão ao exílio, Judá é chamado repetidamente à reforma.","From Solomon's temple to exile, Judah is repeatedly called to reform.","Del templo de Salomón al exilio, Judá es llamado repetidamente a la reforma.","Du temple de Salomon à l'exil, Juda est sans cesse appelé à la réforme.","Dal tempio di Salomone all'esilio, Giuda è ripetutamente chiamato alla riforma.","Von Salomos Tempel bis zum Exil wird Juda immer wieder zur Umkehr gerufen."),chars(["Salomão","Asa","Josafá","Ezequias","Josias"],["Solomon","Asa","Jehoshaphat","Hezekiah","Josiah"],["Salomón","Asa","Josafat","Ezequías","Josías"],["Salomon","Asa","Josaphat","Ézéchias","Josias"],["Salomone","Asa","Giosafat","Ezechia","Giosia"],["Salomo","Asa","Joschafat","Hiskia","Josia"]),[
  stage("solomon",1,9,"Salomão e o templo","Solomon and the temple","Salomón y el templo","Salomon et le temple","Salomone e il tempio","Salomo und der Tempel"),stage("early-kings",10,20,"Reino dividido e primeiros reis","Divided kingdom and early kings","Reino dividido y primeros reyes","Royaume divisé et premiers rois","Regno diviso e primi re","Geteiltes Reich und frühe Könige"),stage("decline",21,28,"Declínio, crises e reformas","Decline, crises and reforms","Declive, crisis y reformas","Déclin, crises et réformes","Declino, crisi e riforme","Niedergang, Krisen und Reformen"),stage("final-reforms",29,35,"Ezequias e Josias renovam o culto","Hezekiah and Josiah renew worship","Ezequías y Josías renuevan el culto","Ézéchias et Josias renouvellent le culte","Ezechia e Giosia rinnovano il culto","Hiskia und Josia erneuern den Gottesdienst"),stage("exile",36,36,"Queda, exílio e esperança","Fall, exile and hope","Caída, exilio y esperanza","Chute, exil et espérance","Caduta, esilio e speranza","Fall, Exil und Hoffnung")]);

export const ezra = book("ezra",15,10,names("Esdras","Ezra","Esdras","Esdras","Esdra","Esra"),names("O povo regressa do exílio, reconstrói o templo e renova a aliança.","The people return from exile, rebuild the temple and renew the covenant.","El pueblo regresa del exilio, reconstruye el templo y renueva el pacto.","Le peuple revient de l'exil, reconstruit le temple et renouvelle l'alliance.","Il popolo torna dall'esilio, ricostruisce il tempio e rinnova l'alleanza.","Das Volk kehrt aus dem Exil zurück, baut den Tempel wieder auf und erneuert den Bund."),chars(["Ciro","Zorobabel","Esdras"],["Cyrus","Zerubbabel","Ezra"],["Ciro","Zorobabel","Esdras"],["Cyrus","Zorobabel","Esdras"],["Ciro","Zorobabele","Esdra"],["Kyrus","Serubbabel","Esra"]),[stage("return",1,2,"O primeiro regresso","The first return","El primer regreso","Le premier retour","Il primo ritorno","Die erste Rückkehr"),stage("temple",3,6,"Reconstrução do templo","Rebuilding the temple","Reconstrucción del templo","Reconstruction du temple","Ricostruzione del tempio","Wiederaufbau des Tempels"),stage("ezra-return",7,8,"Esdras regressa a Jerusalém","Ezra returns to Jerusalem","Esdras regresa a Jerusalén","Esdras revient à Jérusalem","Esdra torna a Gerusalemme","Esra kehrt nach Jerusalem zurück"),stage("renewal",9,10,"Confissão e renovação","Confession and renewal","Confesión y renovación","Confession et renouvellement","Confessione e rinnovamento","Bekenntnis und Erneuerung")]);

export const nehemiah = book("nehemiah",16,13,names("Neemias","Nehemiah","Nehemías","Néhémie","Neemia","Nehemia"),names("Muros e comunidade são reconstruídos por oração, coragem e perseverança.","Walls and community are rebuilt through prayer, courage and perseverance.","Los muros y la comunidad son reconstruidos con oración, valor y perseverancia.","Les murs et la communauté sont reconstruits par la prière, le courage et la persévérance.","Le mura e la comunità vengono ricostruite con preghiera, coraggio e perseveranza.","Mauern und Gemeinschaft werden durch Gebet, Mut und Ausdauer wiederaufgebaut."),chars(["Neemias","Esdras","Sambalate"],["Nehemiah","Ezra","Sanballat"],["Nehemías","Esdras","Sanbalat"],["Néhémie","Esdras","Sanballat"],["Neemia","Esdra","Sanballat"],["Nehemia","Esra","Sanballat"]),[stage("call",1,2,"O chamado para reconstruir","The call to rebuild","El llamado a reconstruir","L'appel à reconstruire","La chiamata a ricostruire","Der Ruf zum Wiederaufbau"),stage("walls",3,7,"Muros erguidos em meio à oposição","Walls raised amid opposition","Muros levantados en medio de oposición","Murs relevés malgré l'opposition","Mura innalzate nonostante l'opposizione","Mauern trotz Widerstand errichtet"),stage("word",8,10,"A Palavra renova o povo","The Word renews the people","La Palabra renueva al pueblo","La Parole renouvelle le peuple","La Parola rinnova il popolo","Das Wort erneuert das Volk"),stage("dedication",11,13,"Dedicação e reforma da comunidade","Dedication and community reform","Dedicación y reforma de la comunidad","Dédicace et réforme de la communauté","Dedicazione e riforma della comunità","Einweihung und Reform der Gemeinschaft")]);

export const esther = book("esther",17,10,names("Ester","Esther","Ester","Esther","Ester","Ester"),names("A providência invisível de Deus preserva o seu povo no império persa.","God's unseen providence preserves his people in the Persian empire.","La providencia invisible de Dios preserva a su pueblo en el imperio persa.","La providence invisible de Dieu préserve son peuple dans l'empire perse.","La provvidenza invisibile di Dio preserva il suo popolo nell'impero persiano.","Gottes unsichtbare Vorsehung bewahrt sein Volk im Perserreich."),chars(["Ester","Mardoqueu","Hamã","Assuero"],["Esther","Mordecai","Haman","Ahasuerus"],["Ester","Mardoqueo","Amán","Asuero"],["Esther","Mardochée","Haman","Assuérus"],["Ester","Mardocheo","Aman","Assuero"],["Ester","Mordechai","Haman","Ahasveros"]),[stage("palace",1,2,"Ester torna-se rainha","Esther becomes queen","Ester se convierte en reina","Esther devient reine","Ester diventa regina","Ester wird Königin"),stage("threat",3,4,"A ameaça e a decisão corajosa","The threat and courageous decision","La amenaza y la decisión valiente","La menace et la décision courageuse","La minaccia e la decisione coraggiosa","Die Bedrohung und mutige Entscheidung"),stage("reversal",5,7,"A grande reviravolta","The great reversal","El gran cambio","Le grand renversement","Il grande capovolgimento","Die große Wende"),stage("deliverance",8,10,"Livramento e festa de Purim","Deliverance and the feast of Purim","Liberación y fiesta de Purim","Délivrance et fête de Pourim","Liberazione e festa di Purim","Befreiung und Purimfest")]);

export const restorationBooks = [secondChronicles, ezra, nehemiah, esther];
